name: slide_to_submit_button
description: A customizable slide-to-submit button with animation and styling options.
version: 1.0.1
homepage: https://github.com/AbdullahAlMamun12/slide_to_submit
repository: https://github.com/AbdullahAlMamun12/slide_to_submit
issue_tracker: https://github.com/AbdullahAlMamun12/slide_to_submit/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/arrow_right.png

topics:
  - button
  - slider
  - submit
  - swipe

screenshots:
  - description: "Slide to submit button in action"
    path: screenshots/demo.gif